### ISSUE TITLE
Is this working with Deluge v2?

### ISSUE THREAD

**Issue by zimmertr** [chrisbergeron/deluge-grafana#2]
I get the following on run:
```
> docker logs -f deluge-exporter
Traceback (most recent call last):
  File "/deluge_exporter.py", line 288, in <module>
    REGISTRY.register(DelugeCollector())
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/core.py", line 96, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/core.py", line 136, in _get_names
    for metric in desc_func():
  File "/deluge_exporter.py", line 218, in collect
    client.connect()
  File "/usr/local/lib/python3.7/site-packages/deluge_client/client.py", line 74, in connect
    self._detect_deluge_version()
  File "/usr/local/lib/python3.7/site-packages/deluge_client/client.py", line 112, in _detect_deluge_version
    result = self._socket.recv(1)
  File "/usr/local/lib/python3.7/ssl.py", line 1037, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.7/ssl.py", line 913, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out
```

**Comment by ngosang** [comment]
Yes, it's working for me. Check the latest dashboard #3

**Comment by zimmertr** [comment]
Thanks for the response! I've since moved on to rTorrent. I'll close this as per your response.
